title: Mohamed Achref Karoui
logo: /assets/achref.png
description: Junior data engineer with a strong background in statistical analysis and machine learning. Motivated and passionate, I am capable of transforming complex data into valuable insights to support company growth. I am a cooperative team member and possess good communication practices. I am also highly interested in exploring new technologies and trends in the field of artificial intelligence.
show_downloads: true
theme: jekyll-theme-minimal
